name: 'Argument Counter'
description: 'This action prints out the number of arguments passed in'
author: 'Thejaswi M'
inputs:
  arguments-to-count: 
    description: 'arguments to count'
    required: true
    default: ''
outputs:
  arg-count:
    description: "Count of arguments passed in"
    value: ${{ steps.return-result.outputs.num-args }}
runs:
  using: "composite"
  steps:
    - name: Print arguments if any
      run: |
        echo Arguments: ${{ inputs.arguments-to-count }}.
      shell: bash
    - id: return-result
      run: |
        count="$(bash "${{ github.action_path }}/count-args.sh" ${{ inputs.arguments-to-count }})"
        echo "num-args=$count" >> "$GITHUB_OUTPUT"
      shell: bash
branding:
  icon: 'aperture'
  color: 'gray-dark'
